#! /bin/bash

# This script installs commands for tiling to the end of the keys file
# it was created by user PPC and released in January 2020 under GPLv3 
# One-third tiling, alternate methods and other changes were added by MX Linux Devs October 2020

TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAIN="mxfb-tiles"

MESSAGE1=$"This script will back up your current keys file, then install commands for tiling to the end of the file. \n
</b>"
HINT1=$"1/2 screen, 1/4 screen, 1/3 screen and restore \n"
HINT2=$"Multiple key options for different keyboards and users"
TITLE1=$"OK to proceed?"
MESSAGE2=$"The code has been inserted successfully. Now there are 2 methods to do the tiling</b>"
METHOD1=$"<u>Modifier + Number</u> 
Modifier: <i>Control</i> (number keys) or <i>Alt</i> (keypad)
Number: 1-4: half, 5-8: quarter; 9: third (left); 0: restore"
METHOD2=$"<u>Modifier + Arrow</u>
--Alt + Arrow, half 
--Alt + LogoKey + Arrow, quarter
--Unavailable: 1/3, restore \n
NOTE: The keypad must be set to \"NumLock on\""
TITLE2=$"Usage options"

##begin first message box
yad --text="


<b>$MESSAGE1 \n
<b>--$HINT1
--$HINT2</b>" --title=$"$TITLE1" --window-icon=/usr/share/icons/mxflux.png --geometry=400x40 --text-align=center 

##end first message box

if [ ! "$?" = "0" ]; then
    exit 0
fi

cp ~/.fluxbox/keys ~/.fluxbox/keys_BAK

echo "## BASIC WINDOW TILING ##

#---------------------------------------------------------------
# Control + number keys
#---------------------------------------------------------------
# Make active window 1/2 of the screen 
Control 1 :MacroCmd {ResizeTo 50% 100%} {MoveTo 00 00 Left} 
Control 2 :MacroCmd {ResizeTo 50% 100%} {MoveTo 00 00 Right} 
Control 3 :MacroCmd {ResizeTo 100% 50%} {MoveTo 00 00 Up} 
Control 4 :MacroCmd {ResizeTo 100% 50%} {MoveTo 00 00 Bottom} 
# Make active window 1/4 of the screen on the upper left 
Control 5 :MacroCmd {ResizeTo 50% 50%} {MoveTo 00 00 Up} 
Control 6 :MacroCmd {ResizeTo 50% 50%} {MoveTo 00 00 TopRight} 
Control 7 :MacroCmd {ResizeTo 50% 50%} {MoveTo 00 00 BottomLeft} 
Control 8 :MacroCmd {ResizeTo 50% 50%} {MoveTo 00 00 BottomRight} 
# Make active window 1/3 of the screen on the left
Control 9 :MacroCmd {ResizeTo 33% 100%} {MoveTo 00 00 Left}
# toggle active window: Maximized/ last size 
Control 0 :ToggleCmd {Maximize} {Restore}

#---------------------------------------------------------------
# Alt/Alt-LogoKey + arrow keys
#---------------------------------------------------------------
# Make active window 1/2 of the screen
Mod1 Left        :MacroCmd {ResizeTo 50% 100%} {MoveTo 00 00 Left}
Mod1 Right       :MacroCmd {ResizeTo 50% 100%} {MoveTo 00 00 Right}
Mod1 Up          :MacroCmd {ResizeTo 100% 50%} {MoveTo 00 00 Up}
Mod1 Down        :MacroCmd {ResizeTo 100% 50%} {MoveTo 00 00 Bottom}
# Make active window 1/4 of the screen on the upper left 
Mod1 Mod4 Left  :MacroCmd {ResizeTo 50% 50% } {MoveTo 00 00 TopLeft}
Mod1 Mod4 Up    :MacroCmd {ResizeTo 50% 50% } {MoveTo 00 00 TopRight}
Mod1 Mod4 Down  :MacroCmd {ResizeTo 50% 50% } {MoveTo 00 00 BottomLeft}
Mod1 Mod4 Right :MacroCmd {ResizeTo 50% 50% } {MoveTo 00 00 BottomRight}
# Make active window 1/3 of the screen on the left
# Unavailable
# toggle center / restore
# Unavailable

#---------------------------------------------------------------
# Alt + numpad keys : NumLock on
#---------------------------------------------------------------
Mod1 KP_1 :MacroCmd {ResizeTo 50% 50% } {MoveTo 00 00 BottomLeft}
Mod1 KP_2 :MacroCmd {ResizeTo 100% 50%} {MoveTo 00 00 Bottom}
Mod1 KP_3 :MacroCmd {ResizeTo 50% 50% } {MoveTo 00 00 BottomRight}
Mod1 KP_4 :MacroCmd {ResizeTo 50% 100%} {MoveTo 00 00 Left}
Mod1 KP_6 :MacroCmd {ResizeTo 50% 100%} {MoveTo 00 00 Right}
# Make active window 1/4 of the screen on the upper left 
Mod1 KP_7 :MacroCmd {ResizeTo 50% 50% } {MoveTo 00 00 TopLeft}
Mod1 KP_8 :MacroCmd {ResizeTo 100% 50%} {MoveTo 00 00 Up}
Mod1 KP_9 :MacroCmd {ResizeTo 50% 50% } {MoveTo 00 00 TopRight}
# toggle center / restore
Mod1 KP_5 :MacroCmd {ResizeTo 70% 70% } {MoveTo 00 00 Center}" >> ~/.fluxbox/keys 
fluxbox-remote restart

##begin second message box
yad --text="

<b>$MESSAGE2 \n
<b>$METHOD1 \n
$METHOD2</b>" --title=$"$TITLE2" --window-icon=/usr/share/icons/mxflux.png --geometry=400x40 --text-align=center 


##end second message box


