#! /bin/bash

#This script installs commands for tiling to the end of the keys file
#The commands were worked out by user PPC with the exception of Control 9
#which was developed by MX Linux Devs.

##begin message box
yad --text="


<b>This script will back up your current keys file, then install commands for tiling to the end of the file</b>" --title=$"OK to proceed?" --window-icon=/usr/share/icons/mxflux.png --geometry=400x40 --text-align=center 
##end message box

if [ ! "$?" = "0" ]; then
    exit 0
fi

cp ~/.fluxbox/keys ~/.fluxbox/keys_BAK

echo "## BASIC WINDOW TILING ##
# Make active window 1/2 of the screen 
Control 1 :MacroCmd {ResizeTo 50% 100%} {MoveTo 00 00 Left} 
Control 2 :MacroCmd {ResizeTo 50% 100%} {MoveTo 00 00 Right} 
Control 3 :MacroCmd {ResizeTo 100% 50%} {MoveTo 00 00 Up} 
Control 4 :MacroCmd {ResizeTo 100% 50%} {MoveTo 00 00 Bottom} 
# Make active window 1/4 of the screen on the upper left 
Control 5 :MacroCmd {ResizeTo 50% 50%} {MoveTo 00 00 Up} 
Control 6 :MacroCmd {ResizeTo 50% 50%} {MoveTo 00 00 TopRight} 
Control 7 :MacroCmd {ResizeTo 50% 50%} {MoveTo 00 00 BottomLeft} 
Control 8 :MacroCmd {ResizeTo 50% 50%} {MoveTo 00 00 BottomRight} 
# Make active window 1/3 of the screen on the right
Control 9 :MacroCmd {ResizeTo 33% 100%} {MoveTo 00 00 Right}
# toggle active window: Maximized/ last size 
Control 0 :ToggleCmd {Maximize} {Restore}" >> ~/.fluxbox/keys 
fluxbox-remote restart
