#!/bin/sh

# this script supplies a graphic method of selecting a style
# by default it points to the users style directory

cd ~/.fluxbox/styles

CHOOSESTYLE=`yad --file --width=600 --height=400`

sed -i "/^session[.]styleFile:.*/c\session.styleFile: ~${CHOOSESTYLE#$HOME}"  ~/.fluxbox/init

fluxbox-remote restart
